version: '3.9'
services:
  db:
    image: mongo:4.4-bionic
    container_name: store_db

    ports:
      - ${MONGO_DB_PORT}:27017

    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}

    volumes:
      - ./scripts/initMongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro

  # app:
  #   build:
  #     context: .
  #     dockerfile: ./scripts/Dockerfile
  #   working_dir: /app
  #   command: npm run watch
  #   container_name: store_app
  #   depends_on:
  #     - db
  #   links:
  #     - db
  #   ports:
  #     - ${APP_PORT}:${APP_PORT}

  #   environment:
  #     - MONGO_DB_HOST=db
  #     - MONGO_DB_PORT=27017
  #     - APP_HOST=0.0.0.0

  #   volumes:
  #     - .:/app
