version: '3.9'
services:
  db:
    image: mongo:4.4-bionic
    container_name: store_db
    ports:
      - ${MONGO_DB_PORT}:27017

    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}

    volumes:
      - ./scripts/initMongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro

  # app:
  #   container_name: store_app
  #   command: npm run watch
  #   working_dir: /app
  #   build:
  #     context: .
  #     dockerfile: ./scripts/Dockerfile
  #   volumes:
  #     - .:/app
  #     - '/app/node_modules'
  #   tty: true
  #   ports:
  #     - ${APP_PORT}:4000
  #   depends_on:
  #     - db
